"""Generate the site's five Markdown mirrors using Python 3.10+ (stdlib only).

Run from the repository:
    python scripts/generate_markdown.py
    python scripts/generate_markdown.py --check
    python -B -m unittest discover -s scripts -p "test_*.py"

HTML is the source of truth. Only the five named .md files are written.
The exporter preserves body order, headings, definitions, navigation, footer
text and explicit IDs. It omits the HTML-only skip link, CSS and JSON-LD.
Links lead to the canonical HTML documents; fragment-only links are qualified
with the source filename, so they do not depend on a Markdown renderer's
automatic heading IDs. Unsupported body markup fails rather than losing text.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from html import escape
from html.parser import HTMLParser
from pathlib import Path
import re
import sys
from urllib.parse import quote, unquote, urlsplit


ROOT = Path(__file__).resolve().parent.parent
PAGES = (
    "index.html",
    "three-principles-of-ai-ja.html",
    "three-principles-of-ai-en.html",
    "three-principles-of-ai-agents-ja.html",
    "three-principles-of-ai-agents-en.html",
)
MARKER = "<!-- Generated by scripts/generate_markdown.py."
VOID = set("area base br col embed hr img input link meta param source track wbr".split())
CONTAINERS = set("body header main footer article section nav div aside".split())
INLINE = {"span", "a", "strong", "em", "b", "i", "br"}
HEADINGS = {f"h{level}" for level in range(1, 7)}


@dataclass
class Node:
    tag: str
    attrs: dict[str, str] = field(default_factory=dict)
    children: list[Node | str] = field(default_factory=list)

    def walk(self):
        yield self
        for child in self.children:
            if isinstance(child, Node):
                yield from child.walk()


class DocumentParser(HTMLParser):
    """Small tree builder for these explicit, well-formed static documents."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node("document")
        self.stack = [self.root]

    def handle_starttag(self, tag, attrs):
        node = Node(tag, {key: value or "" for key, value in attrs})
        self.stack[-1].children.append(node)
        if tag not in VOID:
            self.stack.append(node)

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if len(self.stack) == 1 or self.stack[-1].tag != tag:
            raise ValueError(f"Unbalanced HTML closing tag: {tag}")
        self.stack.pop()

    def handle_data(self, data):
        self.stack[-1].children.append(data)

    def parse(self, html: str) -> Node:
        self.feed(html)
        self.close()
        if len(self.stack) != 1:
            raise ValueError(f"Unclosed HTML tag: {self.stack[-1].tag}")
        return self.root


def compact(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def markdown_text(text: str) -> str:
    # Escaping literal syntax keeps future text from turning into Markdown/HTML.
    text = re.sub(r"\s+", " ", text)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return re.sub(r"([\\`*_[\]#!|])", r"\\\1", text)


def destination(href: str, source_name: str) -> str:
    if not href:
        raise ValueError("Empty link destination")
    parts = urlsplit(href)
    if parts.scheme and parts.scheme not in {"https", "http", "mailto"}:
        raise ValueError(f"Unsupported link scheme: {parts.scheme}")
    if href.startswith("//"):
        raise ValueError("Protocol-relative links are not supported")
    if href.startswith("#"):
        href = source_name + href
    # Parentheses and spaces must not terminate a Markdown link.
    return quote(href, safe="/:#?=&%+@,;~!$'-_.")


def anchor(node: Node) -> str:
    identifier = node.attrs.get("id")
    return f'<a id="{escape(identifier, quote=True)}"></a>\n\n' if identifier else ""


def block(content: str) -> str:
    content = content.strip()
    return f"\n\n{content}\n\n" if content else ""


class Renderer:
    def __init__(self, source_name: str):
        self.source_name = source_name

    def inline(self, children: list[Node | str]) -> str:
        return compact("".join(self.render(child) for child in children))

    def render_list(self, node: Node) -> str:
        items = []
        number = int(node.attrs.get("start", "1"))
        for child in node.children:
            if isinstance(child, str) and not child.strip():
                continue
            if not isinstance(child, Node) or child.tag != "li":
                raise ValueError("Lists must contain list items")
            marker = f"{number}. " if node.tag == "ol" else "- "
            if all(isinstance(part, str) or part.tag in INLINE for part in child.children):
                content = self.inline(child.children)
            else:
                content = "".join(self.render(part) for part in child.children
                                  if not isinstance(part, str) or part.strip()).strip()
            lines = content.splitlines()
            if not lines:
                raise ValueError("Empty list item")
            items.append(anchor(child) + marker + lines[0] + "".join(
                "\n" + " " * len(marker) + line if line else "\n"
                for line in lines[1:]
            ))
            number += 1
        return block("\n".join(items))

    def render_definitions(self, node: Node) -> str:
        parts = []
        for child in node.children:
            if isinstance(child, str) and not child.strip():
                continue
            if isinstance(child, Node) and child.tag == "div":
                if child.attrs.get("id"):
                    raise ValueError("Definition group IDs need an explicit export rule")
                parts.extend(part for part in child.children
                             if not isinstance(part, str) or part.strip())
            else:
                parts.append(child)
        if len(parts) % 2:
            raise ValueError("Each definition must have one term and one description")
        items = []
        for term, description in zip(parts[::2], parts[1::2]):
            if not (isinstance(term, Node) and term.tag == "dt"
                    and isinstance(description, Node) and description.tag == "dd"):
                raise ValueError("Expected dt/dd definition pair")
            items.append(anchor(term) + anchor(description)
                         + f"- **{self.inline(term.children)}**: "
                         + self.inline(description.children))
        return block("\n".join(items))

    def render(self, node: Node | str) -> str:
        if isinstance(node, str):
            return markdown_text(node)
        if "skip-link" in node.attrs.get("class", "").split():
            return ""
        tag = node.tag
        prefix = anchor(node)
        if tag in CONTAINERS:
            if all(isinstance(child, str) or child.tag in INLINE for child in node.children):
                return prefix + block(self.inline(node.children))
            return prefix + block("".join(self.render(child) for child in node.children
                                         if not isinstance(child, str) or child.strip()))
        if tag in HEADINGS:
            return prefix + block("#" * int(tag[1]) + " " + self.inline(node.children))
        if tag == "p":
            return prefix + block(self.inline(node.children))
        if tag in {"ol", "ul"}:
            return prefix + self.render_list(node)
        if tag == "dl":
            return prefix + self.render_definitions(node)
        if tag == "hr":
            return prefix + block("---")
        if tag not in INLINE:
            raise ValueError(f"Unsupported body tag: {tag}")
        content = self.inline(node.children)
        if tag == "a":
            href = destination(node.attrs.get("href", ""), self.source_name)
            return prefix + f"[{content}]({href})"
        if tag in {"strong", "b"}:
            return prefix + f"**{content}**"
        if tag in {"em", "i"}:
            return prefix + f"*{content}*"
        if tag == "br":
            return "<br>"
        # Spans include two-line bilingual menu labels and translated subtitles.
        return prefix + " " + content + " "


def parse_page(html: str) -> tuple[Node, str]:
    tree = DocumentParser().parse(html)
    bodies = [node for node in tree.walk() if node.tag == "body"]
    canonicals = [node.attrs.get("href", "") for node in tree.walk()
                  if node.tag == "link" and node.attrs.get("rel") == "canonical"]
    if len(bodies) != 1 or len(canonicals) != 1:
        raise ValueError("Expected one body and one canonical link")
    if urlsplit(canonicals[0]).scheme != "https":
        raise ValueError("The canonical link must use HTTPS")
    ids = [node.attrs["id"] for node in bodies[0].walk() if "id" in node.attrs]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate body IDs")
    return bodies[0], canonicals[0]


def convert_html(html: str, source_name: str) -> str:
    body, canonical = parse_page(html)
    rendered = Renderer(source_name).render(body).strip()
    rendered = re.sub(r"\n[ \t]+\n", "\n\n", rendered)
    rendered = re.sub(r"\n{3,}", "\n\n", rendered)
    note = (f"{MARKER} Do not edit this file directly.\n"
            f"Source: {source_name}\n"
            "Regenerate: python scripts/generate_markdown.py -->")
    return f"{note}\n\n[HTML]({canonical})\n\n{rendered}\n"


def build_outputs(root: Path) -> dict[Path, str]:
    sources = {}
    bodies = {}
    for name in PAGES:
        source = root / name
        if source.is_symlink():
            raise ValueError(f"Refusing a symlink source: {name}")
        html = source.read_text(encoding="utf-8")
        body, _ = parse_page(html)
        tree = DocumentParser().parse(html)
        alternates = [node.attrs for node in tree.walk()
                      if node.tag == "link" and node.attrs.get("type") == "text/markdown"]
        expected = {"rel": "alternate", "type": "text/markdown",
                    "href": Path(name).with_suffix(".md").name}
        if alternates != [expected]:
            raise ValueError(f"Missing or incorrect Markdown alternate link: {name}")
        sources[name] = html
        bodies[name] = body
    # Validate HTML links before exporting all five pages as one batch.
    for name, body in bodies.items():
        for node in body.walk():
            if node.tag != "a":
                continue
            href = node.attrs.get("href", "")
            destination(href, name)
            parts = urlsplit(href)
            if parts.scheme:
                continue
            target = unquote(parts.path) or name
            if target not in bodies:
                raise ValueError(f"Unknown local link in {name}: {href}")
            if parts.fragment and not any(
                item.attrs.get("id") == unquote(parts.fragment)
                for item in bodies[target].walk()
            ):
                raise ValueError(f"Missing fragment in {name}: {href}")
    return {root / Path(name).with_suffix(".md"): convert_html(html, name)
            for name, html in sources.items()}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Check generated files without writing; exit 1 if stale.")
    args = parser.parse_args(argv)
    try:
        outputs = build_outputs(ROOT)
        for path in outputs:
            if path.is_symlink():
                raise ValueError(f"Refusing a symlink output: {path.name}")
            if path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER):
                raise ValueError(f"Refusing to overwrite a non-generated file: {path.name}")
        stale = [path for path, content in outputs.items()
                 if not path.exists() or path.read_bytes() != content.encode("utf-8")]
        if args.check:
            for path in stale:
                print(f"STALE: {path.name}")
            if not stale:
                print(f"OK: all {len(outputs)} Markdown files are up to date.")
            return 1 if stale else 0
        for path in stale:
            path.write_bytes(outputs[path].encode("utf-8"))
            print(f"Generated: {path.name}")
        print(f"OK: {len(outputs)} Markdown files; {len(stale)} updated.")
        return 0
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
